driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_image: chef/chef
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: debian:7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: centos-5
  driver:
    image: centos:5
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - /usr/bin/yum install -y initscripts net-tools wget

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install tar which initscripts

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum clean all
      - RUN yum -y install net-tools lsof

- name: fedora-latest
  driver:
    image: fedora:latest
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN dnf -y install tar yum

- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https net-tools -y

- name: opensuse-13.2
  driver:
    image: opensuse:13.2
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive

- name: opensuse-42.1
  driver:
    image: opensuse:42.1
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive

suites:
  - name: default
    run_list:
      - recipe[rsyslog::default]
  - name: relp
    run_list:
      - recipe[rsyslog::client]
    attributes:
      rsyslog:
        use_relp: true
        custom_remote:
            - server: 10.0.0.45
              logs: auth.*,mail.*
              port: 555
              protocol: udp
            - server: 10.1.1.33
              logs: authpriv.*,cron.*,daemon.*
              port: 654
              protocol: tcp
              remote_template: RSYSLOG_SyslogProtocol23Format
  - name: client
    run_list:
      - recipe[rsyslog_test::client]
    attributes:
      rsyslog:
        server_ip: 10.0.0.50
        custom_remote:
            - server: 10.0.0.45
              logs: auth.*,mail.*
              port: 555
              protocol: udp
            - server: 10.1.1.33
              logs: authpriv.*,cron.*,daemon.*
              port: 654
              protocol: tcp
              remote_template: RSYSLOG_SyslogProtocol23Format
  - name: server
    run_list:
      - recipe[rsyslog_test::server]
  - name: input_file_provider
    run_list:
      - recipe[rsyslog_test::input_file_provider]
